services:
  pg:
    # https://hub.docker.com/_/postgres
    image: postgres:alpine
    network_mode: "host"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db0
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test", "-d", "db0"]
      interval: 10s
      timeout: 5s
      retries: 5
  mysql:
    # https://hub.docker.com/_/mysql
    image: mysql:8
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: db0
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "test", "-ptest"]
      interval: 10s
      timeout: 5s
      retries: 10
